FROM node:10.15.3

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libglu1-mesa

WORKDIR /opt/src
COPY . .

ENV NODE_ENV=production

RUN npm install -g gatsby-cli
RUN npm install
RUN npm run build

EXPOSE 9000

CMD npm run serve

